# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 10:09
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musicants', '0026_auto_20170331_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicant',
            name='musicant',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='musicant',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 7, 10, 8, 37, 546011, tzinfo=utc), verbose_name='date published'),
        ),
    ]
