# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 06:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicants', '0028_remove_musicant_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musicant',
            old_name='musicant',
            new_name='user',
        ),
    ]
