# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 07:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music_portal', '0004_sing_in_password'),
        ('musicants', '0029_auto_20170408_0658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicant',
            name='user',
        ),
        migrations.AddField(
            model_name='musicant',
            name='musicant',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='music_portal.Sing_in'),
            preserve_default=False,
        ),
    ]
