# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicants',
            name='instrument',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='musicants',
            name='tipe_of_music',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
