# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicants', '0003_remove_musicants_instrument'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicants',
            name='instrument',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
