# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 06:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicants', '0005_auto_20170324_0555'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Musicants',
            new_name='Musicant',
        ),
    ]
