# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicants', '0006_auto_20170324_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicant',
            name='instrument',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='musicant',
            name='tipe_of_music',
            field=models.CharField(default='', max_length=100),
        ),
    ]
