# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicants', '0007_auto_20170324_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicant',
            name='instrument',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
