# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicants', '0008_auto_20170324_0625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musicant',
            old_name='tipe_of_music',
            new_name='type_of_music',
        ),
        migrations.AlterField(
            model_name='musicant',
            name='instrument',
            field=models.CharField(default='', max_length=200),
        ),
    ]
