# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 08:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicants', '0010_auto_20170324_0713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicant',
            name='pub_date',
        ),
    ]
