# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 08:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicants', '0011_remove_musicant_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicant',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 24, 8, 46, 0, 118934), verbose_name='date published'),
        ),
    ]
