# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 15:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('musicants', '0012_musicant_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicant',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 24, 15, 9, 19, 877461, tzinfo=utc), verbose_name='date published'),
        ),
    ]
