# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 07:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('musicants', '0014_auto_20170328_0643'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.AlterField(
            model_name='musicant',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 28, 7, 5, 39, 625619, tzinfo=utc), verbose_name='date published'),
        ),
    ]
