# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 15:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('musicants', '0021_auto_20170328_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicant',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 29, 15, 19, 22, 112610, tzinfo=utc), verbose_name='date published'),
        ),
    ]
