# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 16:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('musicants', '0022_auto_20170329_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicant',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 29, 16, 33, 40, 663821, tzinfo=utc), verbose_name='date published'),
        ),
    ]
