# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 16:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('musicants', '0023_auto_20170329_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicant',
            name='level',
            field=models.CharField(choices=[('elementary', 'Начальный'), ('average', 'Средний'), ('high', 'Высокий'), ('professional', 'Профессионал')], default='', max_length=50, verbose_name='Уровень владения инструментом'),
        ),
        migrations.AlterField(
            model_name='musicant',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 30, 16, 1, 41, 848238, tzinfo=utc), verbose_name='date published'),
        ),
    ]
