# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 14:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('musicants', '0025_auto_20170331_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicant',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 31, 14, 15, 6, 860473, tzinfo=utc), verbose_name='date published'),
        ),
    ]
