# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicants', '0028_auto_20170408_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicant',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
