# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sing_in',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='login',
            name='email',
        ),
    ]
